### ISSUE TITLE
Need clarification about the server part

### ISSUE THREAD

**Issue by dgoulet** [ioerror/mpOTR#1]
Hey!

Can you (or someone) clarify this part of the draft:

"Each party then sends its nickname and a random number to the server, which are shared by the server and used to generate a unique, non-secret session ID which is shared between all parties."

Does this means that mpOTR would need a server component? If yes, doesn't it defeat the purpose of OTR having an end to end encryption with any kind of IM protocol?

Thanks!

**Comment by ioerror** [comment]
I believe this merely requires that we push the values into a channel that shares it with all other interested parties.

**Comment by dgoulet** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Right but which component (or who) actually generates that non-secret
session ID?

Of what I understand of your answer is that it's basically a broadcast
mechanism from the person initiating the first message in the room?

Jacob Appelbaum:

> I believe this merely requires that we push the values into a
> channel that shares it with all other interested parties.
> 
> — Reply to this email directly or view it on GitHub 
> https://github.com/ioerror/mpOTR/issues/1#issuecomment-13585253.
> 
> -----BEGIN PGP SIGNATURE-----
> Version: GnuPG v1.4.12 (GNU/Linux)

iQEcBAEBCgAGBQJRHXaHAAoJEELoaioR9I02490IAIsbL9lT7fAX5lq4jc4jWHEZ
VYrwulbCfcyTvSXVlj4kUskuZCqTlZPbX7MtrFrO5J+QV87jHR66JntPlDdzwF3a
cValrBXjXr+ELjkzILEPqOZtOzAzc93QycIqPgO6JHet79CX4l6NlAASM13vN9An
aWS1TO2CG6qpixc3pn9sFkEB5/DW+9e1naYz/opvuxo9RX57hq1cfAfRlKPKrnhx
FoJKfmGc7EkJTlxIEmeTvB62N5rVI3bBMwSFJ9G5dOQm0ke/BOmA6LbvHePrbxMJ
OOBrXtpeyuVAXPHjnBElZgKrMWlWS7miSORGo5US5ccgyOKVVFylbiRmea6h7GY=
=LpF8
-----END PGP SIGNATURE-----

**Comment by ioerror** [comment]
Each client - the server is just a dumb relay.

**Comment by ioerror** [comment]
If this is unclear, perhaps send a pull request that makes it more clear so that we can have the spec updated?
